<?php

namespace App\Http\Resources\Assessment;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class AssessmentFormTemplateResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'id'              => $this->id,
            'uuid'            => $this->uuid,
            'code'            => $this->code,
            'name'            => $this->name,
            'name_kh'         => $this->name_kh,
            'description'     => $this->description,
            'description_kh'  => $this->description_kh,
            'category'        => $this->category,
            'is_locked'       => (bool) $this->is_locked,
            'settings'        => $this->settings,
            'version_notes'   => $this->version_notes,
            'review_notes'    => $this->review_notes,
            'review_status'   => $this->review_status,
            'submitted_by'    => $this->whenLoaded('submittedBy', fn () => [
                'id'   => $this->submittedBy->id,
                'name' => trim($this->submittedBy->first_name.' '.$this->submittedBy->last_name),
            ], $this->submitted_by),
            'submitted_at'    => $this->submitted_at?->toIso8601String(),
            'review_started_by' => $this->whenLoaded('reviewStartedBy', fn () => [
                'id'   => $this->reviewStartedBy->id,
                'name' => trim($this->reviewStartedBy->first_name.' '.$this->reviewStartedBy->last_name),
            ], $this->review_started_by),
            'review_started_at' => $this->review_started_at?->toIso8601String(),
            'reviewed_by'     => $this->whenLoaded('reviewedBy', fn () => [
                'id'   => $this->reviewedBy->id,
                'name' => trim($this->reviewedBy->first_name.' '.$this->reviewedBy->last_name),
            ], $this->reviewed_by),
            'reviewed_at'     => $this->reviewed_at?->toIso8601String(),
            'duplicated_from_template_id' => $this->duplicated_from_template_id,
            'duplicated_from_version' => $this->duplicated_from_version,
            'restored_from_template_id' => $this->restored_from_template_id,
            'restored_from_version' => $this->restored_from_version,
            'module'          => $this->module,
            'status'          => $this->status,
            'current_version' => $this->current_version,
            'is_draft'        => $this->status === 'draft',
            'is_published'    => $this->status === 'published',
            'is_archived'     => $this->status === 'archived',
            'is_under_review' => in_array($this->review_status, ['submitted', 'in_review'], true),
            'is_review_approved' => $this->review_status === 'approved',
            'is_review_rejected' => $this->review_status === 'rejected',
            'published_by'    => $this->whenLoaded('publishedBy', fn () => [
                'id'   => $this->publishedBy->id,
                'name' => trim($this->publishedBy->first_name.' '.$this->publishedBy->last_name),
            ]),
            'archived_by'     => $this->whenLoaded('archivedBy', fn () => [
                'id'   => $this->archivedBy->id,
                'name' => trim($this->archivedBy->first_name.' '.$this->archivedBy->last_name),
            ]),
            'published_at'    => $this->published_at?->toIso8601String(),
            'archived_at'     => $this->archived_at?->toIso8601String(),
            'created_by'      => $this->created_by,
            'updated_by'      => $this->updated_by,
            'created_at'      => $this->created_at?->toIso8601String(),
            'updated_at'      => $this->updated_at?->toIso8601String(),
            'versions'        => $this->whenLoaded('versions', fn () => $this->versions->map(fn ($version) => [
                'id'             => $version->id,
                'version_number' => $version->version_number,
                'label'          => $version->label,
                'change_summary' => $version->change_summary,
                'publish_notes'  => $version->change_summary,
                'version_notes'  => data_get($version->snapshot, 'template.version_notes'),
                'review_notes'   => data_get($version->snapshot, 'template.review_notes'),
                'review_status'  => data_get($version->snapshot, 'template.review_status'),
                'submitted_by'   => [
                    'id' => data_get($version->snapshot, 'template.submitted_by'),
                    'name' => data_get($version->snapshot, 'template.submitted_by_name'),
                ],
                'submitted_at'   => data_get($version->snapshot, 'template.submitted_at'),
                'review_started_by' => [
                    'id' => data_get($version->snapshot, 'template.review_started_by'),
                    'name' => data_get($version->snapshot, 'template.review_started_by_name'),
                ],
                'review_started_at' => data_get($version->snapshot, 'template.review_started_at'),
                'reviewed_by'    => [
                    'id' => data_get($version->snapshot, 'template.reviewed_by'),
                    'name' => data_get($version->snapshot, 'template.reviewed_by_name'),
                ],
                'reviewed_at'    => data_get($version->snapshot, 'template.reviewed_at'),
                'duplicated_from_template_id' => data_get($version->snapshot, 'template.duplicated_from_template_id'),
                'duplicated_from_version' => data_get($version->snapshot, 'template.duplicated_from_version'),
                'restored_from_template_id' => data_get($version->snapshot, 'template.restored_from_template_id'),
                'restored_from_version' => data_get($version->snapshot, 'template.restored_from_version'),
                'published_at'   => $version->published_at?->toIso8601String(),
                'published_by'   => $version->published_by,
                'is_current'     => (bool) $version->is_current,
                'created_at'     => $version->created_at?->toIso8601String(),
            ])->values()),
            'sections'        => $this->whenLoaded('sections', fn () => $this->sections->map(fn ($section) => [
                'id'              => $section->id,
                'template_id'     => $section->template_id,
                'parent_id'       => $section->parent_id,
                'code'            => $section->code,
                'title'           => $section->title,
                'title_kh'        => $section->title_kh,
                'description'     => $section->description,
                'description_kh'  => $section->description_kh,
                'sort_order'      => $section->sort_order,
                'is_repeatable'   => (bool) $section->is_repeatable,
                'max_repeats'     => $section->max_repeats,
                'print_visible'   => (bool) $section->print_visible,
                'scoring_weight'  => $section->scoring_weight,
                'settings'        => $section->settings,
                'questions'       => $section->questions->map(fn ($question) => [
                    'id'                => $question->id,
                    'uuid'              => $question->uuid,
                    'template_id'       => $question->template_id,
                    'section_id'        => $question->section_id,
                    'question_type_id'  => $question->question_type_id,
                    'question_type_key' => $question->questionType?->key,
                    'parent_question_id'=> $question->parent_question_id,
                    'code'              => $question->code,
                    'label'             => $question->label,
                    'label_kh'          => $question->label_kh,
                    'help_text'         => $question->help_text,
                    'help_text_kh'      => $question->help_text_kh,
                    'placeholder'       => $question->placeholder,
                    'placeholder_kh'    => $question->placeholder_kh,
                    'sort_order'        => $question->sort_order,
                    'is_required'       => (bool) $question->is_required,
                    'is_scored'         => (bool) $question->is_scored,
                    'max_score'         => $question->max_score,
                    'scoring_weight'    => $question->scoring_weight,
                    'print_visible'     => (bool) $question->print_visible,
                    'validation_rules'  => $question->validation_rules,
                    'conditional_logic' => $question->conditional_logic,
                    'calculation_formula'=> $question->calculation_formula,
                    'settings'          => $question->settings,
                    'options'           => $question->options->map(fn ($option) => [
                        'id'          => $option->id,
                        'label'       => $option->label,
                        'label_kh'    => $option->label_kh,
                        'value'       => $option->value,
                        'score_value' => $option->score_value,
                        'risk_tag'    => $option->risk_tag,
                        'color_code'  => $option->color_code,
                        'sort_order'  => $option->sort_order,
                        'is_other'    => (bool) $option->is_other,
                        'settings'    => $option->settings,
                    ])->values(),
                ])->values(),
            ])->values()),
        ];
    }
}
